### ISSUE TITLE
ED figures and SI tables need to be added to README.md and run script

### ISSUE THREAD

**Issue by bolliger32** [bolliger32/gpl-covid#201]
The code to generate each of the following figures should be in the `run` script and referenced in the readme:

- [x] ED Fig 2 (@luna983 )
- [x] ED Figs 3-5 (@sannanphan )
- [x] ED Fig 6 (@jeanettelt )
- [x] SI Table 2 (@luna983 ) I feel like this might not be a code-generated table - If that's the case, just note that in the run and README files and we're good!
- [x] SI Tables 3-5 (@sannanphan or @jeanettelt ) - If these tables just pop out of another script, just note that in the run and README file and we're good!

**Comment by bolliger32** [comment]
Awesome thanks everyone! I went through and added to @jeanettelt 's last PR to make sure extended data figure source data was numbered correctly and outputting from the correct script. Couple more things:

- [ ] Currently, I don't think we have a source_data file for ED Fig 3 (@jeanettelt / @sannanphan ). Totally could have missed it or accidentally deleted it too - there was a good amount of untangling after the numbering shifts. Could one of you halp me locate that one? Or is that information contained in `ExtendedDataFigure4_cross_valid.csv`?
- [ ] @kendonB I don't think we're outputting source_data for ED Fig 7. Can you add that to the multiple gamma script and add the file to `results/source_data`

**Comment by sannanphan** [comment]
data for A3 is in `ExtendedDataFigure4_cross_valid.csv`

**Comment by bolliger32** [comment]
> data for A3 is in `ExtendedDataFigure4_cross_valid.csv`

@sannanphan great! In my PR I just changed all the indiv files to `ExtendedDataFigure34...` in the code just to clarify. I didn't see the overall csv getting created anywhere. Is there code that aggregates the indiv csvs into the full `results/source_data/ExtendedDataFigure34_cross_valid.csv`?

**Comment by jeanettelt** [comment]
@sannanphan `codes/plotting/extended_data_fig4.do` prev output `results/source_data/ExtendedDataFigure4_cross_valid.csv`

**Comment by sannanphan** [comment]
@jeanettelt I just updated my plotting code so now it should export both csv.

**Comment by bolliger32** [comment]
Awesome! I think all we need is source_data from ED fig 7 (@kendonB ) and we should be good to go!

**Comment by bolliger32** [comment]
closed by #223
