### ISSUE TITLE
"present day" projections raise errors in CI

### ISSUE THREAD

**Issue by bolliger32** [bolliger32/gpl-covid#312]
@kendonB after #311 was merged to master, it looks like master failed the tests. I'm guessing that's b/c it's getting projecting longer and longer each day? We should either skip the checking of this file or have a fixed end date that it projects to, which we can change manually.

**Comment by trinetta** [comment]
Hi! I had a temporary fix for this while updating the code for Fig 2, see [PR #314](https://github.com/bolliger32/gpl-covid/pull/314), not sure if that's where we want to go long term though,

basically moved these 4 files to `models/projections/raw` and added that folder to .gitignore for future pushes
projection_output_daily.csv
raw_projection_output.csv
projection_output_extended_daily.csv
raw_projection_output_extended.csv

**Comment by bolliger32** [comment]
works for me! I think that's fine for now and we can cross this bridge to make it more stable if/when we want

**Comment by bolliger32** [comment]
closed by #314
