### ISSUE TITLE
French daily cases website changed :(

### ISSUE THREAD

**Issue by bolliger32** [bolliger32/gpl-covid#45]
looks like something changed about the french website we were scraping for cases... So now it downloads a blank file with no datestamp. Will want to update the code to handle this (not sure if its temporary or a permanent change)

**Comment by jeanettelt** [comment]
yea...the scraping code does not work anymore because they completely changed the website. we can no longer find confirmed cases by region and day anymore. France has switched to focusing on hospitalization data instead...

**Comment by bolliger32** [comment]
Dang! Can we go with that other site that gets updated every few days? Or will they not have the data anymore either. Should we just remove that scraping script then? And make sure the france code works with the timeseries we do have?

Seems like using the hospitalization data is beyond our current scope but could be a cool thing to look at at some point?

**Comment by jeanettelt** [comment]
The other site last updated data on March 24, so we're not sure if they will continue to update the case data. We managed to scrape data on confirmed cases through March 25, so will go with that for now. Yes, I guess we should just remove the scraping script and use what we have thus far. 

Definitely would be cool to look at hospitalization data later. They also have it at a higher spatial resolution.

**Comment by bolliger32** [comment]
Cool! Let's leave this issue open and mark it as fixed when we've:
1. Removed the scraping code and adjusted README and `run` script
2. Verified whether or not we can still get french data from the aggregating site, and adjusted our code/README accordingly

**Comment by jeanettelt** [comment]
will need to wait to see if the aggregated data we were downloading will have updated again before we resubmit. will update README and appendix after we figure out what data is available later.

**Comment by bolliger32** [comment]
Looks like neither website is being updated, so we're stopping our analysis on 3/25 in france. @jeanettelt do we want to simplify things and just have the aggregate 3/24 dataset + one day of the "daily" data for 3/25?

**Comment by jeanettelt** [comment]
I think the daily data we scraped from the government website is more accurate than the compiled Excel spreadsheet but will let @sannanphan decide what he wants to do re: France epi data.

**Comment by sannanphan** [comment]
@jeanettelt is right @bolliger32 , the compiled file has missing days that we filled with our scrips, in particular march 9 & march 13

**Comment by bolliger32** [comment]
Awesome! then I am closing this issue. Nice work!
