### ISSUE TITLE
ensure region is not covered by an optional and a non-optional policy of the same category

### ISSUE THREAD

**Issue by dpa9694** [bolliger32/gpl-covid#69]
A region subject to `somepolicy` should not also have the "extra treatment" of `somepolicy_opt` when other regions in the super-region get this treatment, since this optional policy doesn't actually effect any new policy treatment for the region that already had `somepolicy`. The same goes for `popwt` versions of `somepolicy`--we should make sure that any sub-regions (that compose the pop-weight of the region) that are encompassed in `somepolicy_popwt` are not also aggregated in `somepolicy_opt_popwt` during any of the days those policies are in place, and vice versa.

**Comment by bolliger32** [comment]
Duplicate of #67

**Comment by dpa9694** [comment]
> 
> 
> Duplicate of #67

oops
