### ISSUE TITLE
resolve merge conflicts in FRA regression files

### ISSUE THREAD

**Issue by bolliger32** [bolliger32/gpl-covid#73]
see comment in #72. It looks like FRA_coefs.csv, FRA_preds.csv, and FRA_reg_data.csv currently have merge conflicts in them

**Comment by jeanettelt** [comment]
yea something weird happened to my git that I didn't fully understand, so I just re ran the FRA do file to get the latest reg output. see #74

**Comment by bolliger32** [comment]
Closed by #74
